version: "3.3"
services:
  grafana_container:
    image: grafana/grafana
    depends_on:
      - mysql_db_container 
    ports:
      - 3000:3000
    volumes:
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./grafana/config/custom.ini:/etc/grafana/grafana.ini

  mysql_db_container:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password   
    env_file:
      - ./.env
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./mysql-data:/var/lib/mysql

  adminer_container:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080
    depends_on: 
      - mysql_db_container